import React, { useEffect, useMemo, useRef, useState } from 'react';
import './App.css';

const TARGET_PLAYER = 300;
const TARGET_TEAM = 850;
const PLAYERS = [
  { id:'rose', name:'Rose', role:'Cheffe de mission', avatar:'R', color:'#e85b93' },
  { id:'gustave', name:'Gustave', role:'Stratège', avatar:'G', color:'#4ea3ff' },
  { id:'jacques', name:'Jacques', role:'Dernier turbo', avatar:'J', color:'#7bd85a' }
];
const MISSIONS = [
  { id:'speed', title:'Rapidité', icon:'⚽', text:'Attrape les ballons avant disparition.' },
  { id:'camera', title:'Caméra secrète', icon:'🔦', text:'Prends les indices hors du faisceau.' },
  { id:'quiz', title:'Quiz', icon:'📖', text:'Réponds avant la fin du chrono.' },
  { id:'memory', title:'Mémoire', icon:'🧩', text:'Retrouve les paires secrètes.' },
  { id:'decode', title:'Décryptage', icon:'🔍', text:'Remets les mots dans l’ordre.' },
  { id:'shoot', title:'Shoot final', icon:'🥅', text:'Tire au bon moment.' }
];
const QUIZ = [
  ['Que veut dire PSG ?', ['Paris Saint-Germain','Petit Super Gardien','Parc Secret Géant'], 0],
  ['Où se trouve le Parc des Princes ?', ['Paris','Marseille','Sur la lune'], 0],
  ['La surprise tombe quel jour ?', ['30 mai','14 juillet','le jour des chaussettes'], 0],
  ['Pour l’ambiance de stade, il faut...', ['chanter fort','chuchoter','faire la sieste'], 0],
  ['Le cadeau final est caché dans...', ['un coffre','un brocoli','un cartable'], 0]
];
const WORDS = ['PARC','PSG','FINALE','ECRAN','BILLET'];
const PAIRS = ['⚽','🏟️','🎟️','🔐','⭐','🏆'];
const fresh = () => ({ rose:0, gustave:0, jacques:0 });
const clamp = (n,a,b)=>Math.max(a,Math.min(b,n));
const shuffle = a => [...a].sort(()=>Math.random()-.5);
function load(){ try{return JSON.parse(localStorage.getItem('brigade30mai')) || fresh()}catch{return fresh()} }

export default function App(){
  const [screen,setScreen]=useState('home');
  const [active,setActive]=useState('rose');
  const [scores,setScores]=useState(load);
  const [mission,setMission]=useState('speed');
  const [last,setLast]=useState(null);
  const player = PLAYERS.find(p=>p.id===active);
  const total = Object.values(scores).reduce((a,b)=>a+b,0);
  const unlocked = total>=TARGET_TEAM && PLAYERS.every(p=>scores[p.id]>=TARGET_PLAYER);
  useEffect(()=>localStorage.setItem('brigade30mai',JSON.stringify(scores)),[scores]);
  const add=(points,label)=>{setScores(s=>({...s,[active]:clamp(s[active]+points,0,9999)}));setLast({points,label,name:player.name});setScreen('missions')};
  const screens={home:<Home setScreen={setScreen}/>,team:<Team active={active} setActive={setActive} scores={scores} setScreen={setScreen}/>,missions:<Missions player={player} scores={scores} total={total} setMission={setMission} setScreen={setScreen} last={last}/>,carnet:<Carnet scores={scores} total={total} setScreen={setScreen}/>,final:<Final scores={scores} total={total} unlocked={unlocked} setScreen={setScreen} reset={()=>setScores(fresh())}/>,rules:<Rules setScreen={setScreen}/>};
  return <div className="app"><div className="stars"/><header><button onClick={()=>setScreen('home')}>QG</button><b>La Brigade du 30 Mai</b><button onClick={()=>setScreen('rules')}>Règles</button></header>{screen==='game'?<Game id={mission} player={player} onDone={add} onExit={()=>setScreen('missions')}/>:screens[screen]}</div>
}
function Medal({p}){return <div className="medal" style={{'--c':p.color}}><span>{p.avatar}</span></div>}
function Bar({v,t}){return <div className="bar"><i style={{width:clamp(v/t*100,0,100)+'%'}}/></div>}
function Title({n,t,s}){return <div className="title"><small>{n}.</small><h1>{t}</h1>{s&&<p>{s}</p>}</div>}
function Home({setScreen}){return <main className="home"><div className="crest"><small>Mission secrète</small><strong>La Brigade du<br/>30 Mai</strong><em>🔐</em></div><p>Trois héros, six missions, un carnet secret et un coffre final.</p><div className="teamrow">{PLAYERS.map(p=><Medal key={p.id} p={p}/>)}</div><button className="gold" onClick={()=>setScreen('team')}>Commencer la mission</button><nav><button onClick={()=>setScreen('team')}>Équipe</button><button onClick={()=>setScreen('carnet')}>Carnet</button><button onClick={()=>setScreen('final')}>Coffre</button></nav></main>}
function Team({active,setActive,scores,setScreen}){return <main><Title n="2" t="Notre équipe" s="Choisis ton héros"/><div className="cards">{PLAYERS.map(p=><button key={p.id} className={'card '+(active===p.id?'on':'')} onClick={()=>setActive(p.id)}><Medal p={p}/><h2>{p.name}</h2><p>{p.role}</p><Bar v={scores[p.id]} t={TARGET_PLAYER}/><b>{scores[p.id]} / {TARGET_PLAYER}</b></button>)}</div><button className="gold" onClick={()=>setScreen('missions')}>Voir les missions</button></main>}
function Missions({player,scores,total,setMission,setScreen,last}){return <main><Title n="3" t="Missions" s="Gagne des points et ouvre les indices"/><section className="panel hero"><Medal p={player}/><div><b>{player.name} joue</b><Bar v={scores[player.id]} t={TARGET_PLAYER}/><span>{scores[player.id]} / {TARGET_PLAYER}</span></div></section>{last&&<div className="toast">+{last.points} points pour {last.name} — {last.label}</div>}<div className="grid">{MISSIONS.map(m=><button key={m.id} className="mission" onClick={()=>{setMission(m.id);setScreen('game')}}><span>{m.icon}</span><b>{m.title}</b><small>{m.text}</small></button>)}</div><section className="panel"><b>Total équipe : {total} / {TARGET_TEAM}</b><Bar v={total} t={TARGET_TEAM}/></section><nav><button onClick={()=>setScreen('team')}>Équipe</button><button onClick={()=>setScreen('carnet')}>Carnet</button><button onClick={()=>setScreen('final')}>Coffre</button></nav></main>}
function Carnet({scores,total,setScreen}){const checks=[scores.rose>=100,scores.gustave>=100,scores.jacques>=100,total>=500,total>=TARGET_TEAM];const clues=['30 mai','Grand écran','Ambiance de stade','Parc des Princes','Cadeau final'];return <main><Title n="4" t="Carnet secret"/><section className="paper">{clues.map((c,i)=><div key={c}><span>Indice {i+1}</span><b>{checks[i]?c:'À découvrir'}</b><em>{checks[i]?'✓':'🔒'}</em></div>)}</section><button className="gold" onClick={()=>setScreen('missions')}>Retour aux missions</button></main>}
function Final({scores,total,unlocked,setScreen,reset}){return <main><Title n="11" t="Coffre final" s={unlocked?'Coffre ouvert':'Coffre verrouillé'}/><section className="panel final"><div className="chest">{unlocked?'🎁':'🔐'}</div>{!unlocked?<>{PLAYERS.map(p=><p key={p.id}>{scores[p.id]>=TARGET_PLAYER?'✅':'🔒'} {p.name} : {scores[p.id]} / {TARGET_PLAYER}</p>)}<p>{total>=TARGET_TEAM?'✅':'🔒'} Équipe : {total} / {TARGET_TEAM}</p></>:<p>Rose, Gustave et Jacques vont vivre la finale de la Ligue des Champions au Parc des Princes, le 30 mai, sur grand écran, dans l’ambiance du stade.</p>}</section><button className="gold" onClick={()=>setScreen('missions')}>Retour</button><button onClick={reset}>Remettre à zéro</button></main>}
function Rules({setScreen}){return <main><Title n="12" t="Règles"/><section className="paper"><p>Chaque héros doit atteindre son score personnel.</p><p>L’équipe doit atteindre le score collectif.</p><p>Les indices se débloquent dans le carnet.</p></section><button className="gold" onClick={()=>setScreen('home')}>Retour au QG</button></main>}
function Frame({title,player,time,score,onExit,children}){return <main><div className="gameHead"><Medal p={player}/><h1>{title}</h1><b>{time}s</b><b>{score}</b></div>{children}<button onClick={onExit}>Retour aux missions</button></main>}
function Game({id,player,onDone,onExit}){const map={speed:Speed,camera:Camera,quiz:Quiz,memory:Memory,decode:Decode,shoot:Shoot};const C=map[id]||Speed;return <C player={player} onDone={onDone} onExit={onExit}/>}
function Speed({player,onDone,onExit}){const[time,setTime]=useState(18),[score,setScore]=useState(0),[balls,setBalls]=useState([]);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);const s=setInterval(()=>{const id=Math.random();const b={id,x:10+Math.random()*80,y:15+Math.random()*70,gold:Math.random()<.25};setBalls(a=>[...a,b]);setTimeout(()=>setBalls(a=>a.filter(z=>z.id!==id)),1000+Math.random()*900)},650);return()=>{clearInterval(t);clearInterval(s)}},[]);useEffect(()=>{if(time<=0)onDone(ref.current,'Rapidité')},[time]);return <Frame title="Rapidité" player={player} time={Math.max(time,0)} score={score} onExit={onExit}><div className="field">{balls.map(b=><button key={b.id} className={'ball '+(b.gold?'golden':'')} style={{left:b.x+'%',top:b.y+'%'}} onClick={()=>{setScore(s=>s+(b.gold?22:12));setBalls(a=>a.filter(z=>z.id!==b.id))}}>{b.gold?'🏆':'⚽'}</button>)}</div></Frame>}
function Camera({player,onDone,onExit}){const[time,setTime]=useState(20),[score,setScore]=useState(0),[items,setItems]=useState([]),[beam,setBeam]=useState(0);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);const b=setInterval(()=>setBeam(v=>(v+10)%100),120);const s=setInterval(()=>{const id=Math.random();const it={id,x:8+Math.random()*84,y:18+Math.random()*62,trap:Math.random()<.25};setItems(a=>[...a,it]);setTimeout(()=>setItems(a=>a.filter(z=>z.id!==id)),2200)},850);return()=>{clearInterval(t);clearInterval(b);clearInterval(s)}},[]);useEffect(()=>{if(time<=0)onDone(ref.current,'Caméra secrète')},[time]);return <Frame title="Caméra" player={player} time={Math.max(time,0)} score={score} onExit={onExit}><div className="field"><i className="beam" style={{left:beam+'%'}}/>{items.map(i=><button key={i.id} className={'ball '+(i.trap?'trap':'')} style={{left:i.x+'%',top:i.y+'%'}} onClick={()=>{const caught=Math.abs(i.x-beam)<15;setScore(s=>clamp(s+(i.trap?-12:caught?-8:18),0,999));setItems(a=>a.filter(z=>z.id!==i.id))}}>{i.trap?'🚨':'✉️'}</button>)}</div></Frame>}
function Quiz({player,onDone,onExit}){const[time,setTime]=useState(45),[idx,setIdx]=useState(0),[score,setScore]=useState(0),[qs]=useState(()=>shuffle(QUIZ).slice(0,5));const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(time<=0||idx>=qs.length)onDone(ref.current,'Quiz')},[time,idx]);if(idx>=qs.length)return null;const q=qs[idx];return <Frame title="Quiz" player={player} time={Math.max(time,0)} score={score} onExit={onExit}><section className="panel"><h2>{q[0]}</h2>{q[1].map((a,i)=><button key={a} onClick={()=>{setScore(s=>s+(i===q[2]?24:0));setIdx(x=>x+1)}}>{a}</button>)}</section></Frame>}
function Memory({player,onDone,onExit}){const[time,setTime]=useState(50),[cards,setCards]=useState(()=>shuffle([...PAIRS,...PAIRS]).map((v,i)=>({id:i,v,open:false,found:false}))),[first,setFirst]=useState(null),[score,setScore]=useState(0),[lock,setLock]=useState(false);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(time<=0||cards.every(c=>c.found))onDone(ref.current,'Mémoire')},[time,cards]);const flip=c=>{if(lock||c.open||c.found)return;setCards(a=>a.map(x=>x.id===c.id?{...x,open:true}:x));if(!first){setFirst(c);return}if(first.v===c.v){setScore(s=>s+18);setCards(a=>a.map(x=>x.id===first.id||x.id===c.id?{...x,found:true,open:true}:x));setFirst(null)}else{setLock(true);setTimeout(()=>{setCards(a=>a.map(x=>x.id===first.id||x.id===c.id?{...x,open:false}:x));setFirst(null);setLock(false)},700)}};return <Frame title="Mémoire" player={player} time={Math.max(time,0)} score={score} onExit={onExit}><div className="mem">{cards.map(c=><button key={c.id} onClick={()=>flip(c)}>{(c.open||c.found)?c.v:'?'}</button>)}</div></Frame>}
function Decode({player,onDone,onExit}){const[time,setTime]=useState(45),[idx,setIdx]=useState(0),[built,setBuilt]=useState(''),[score,setScore]=useState(0);const word=WORDS[idx]||'';const letters=useMemo(()=>shuffle(word.split('')),[word]);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(time<=0||idx>=WORDS.length)onDone(ref.current,'Décryptage')},[time,idx]);if(idx>=WORDS.length)return null;return <Frame title="Décryptage" player={player} time={Math.max(time,0)} score={score} onExit={onExit}><section className="panel"><div className="slots">{word.split('').map((_,i)=><span key={i}>{built[i]||''}</span>)}</div>{letters.map((l,i)=><button key={l+i} onClick={()=>{const n=built+l;if(word.startsWith(n)){setBuilt(n);if(n===word){setScore(s=>s+26);setTimeout(()=>{setBuilt('');setIdx(x=>x+1)},400)}}else setBuilt('')}}>{l}</button>)}</section></Frame>}
function Shoot({player,onDone,onExit}){const[time,setTime]=useState(30),[score,setScore]=useState(0),[pos,setPos]=useState(0),[dir,setDir]=useState(1);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);const m=setInterval(()=>setPos(p=>{let n=p+dir*4;if(n>100||n<0){setDir(d=>-d);n=clamp(n,0,100)}return n}),45);return()=>{clearInterval(t);clearInterval(m)}},[dir]);useEffect(()=>{if(time<=0)onDone(ref.current,'Shoot final')},[time]);return <Frame title="Shoot" player={player} time={Math.max(time,0)} score={score} onExit={onExit}><section className="panel shoot"><div className="gauge"><i style={{left:pos+'%'}}/></div><button className="gold" onClick={()=>{const d=Math.abs(pos-50);setScore(s=>s+(d<8?30:d<20?14:0))}}>Tirer !</button></section></Frame>}
