import React,{useEffect,useMemo,useRef,useState}from'react';
import roseAvatar from'./assets/Rosee.png';
import gustaveAvatar from'./assets/gustave.png';
import jacquesAvatar from'./assets/Jacquespng.png';
import'./App.css';

const AVATARS={rose:roseAvatar,gustave:gustaveAvatar,jacques:jacquesAvatar};
const TARGET_PLAYER=300,TARGET_TEAM=850;
const PLAYERS=[
  {id:'rose',name:'Rose',role:'Cheffe de mission',avatar:'R',color:'#e85b93'},
  {id:'gustave',name:'Gustave',role:'Stratège',avatar:'G',color:'#4ea3ff'},
  {id:'jacques',name:'Jacques',role:'Dernier turbo',avatar:'J',color:'#7bd85a'}
];
const MISSIONS=[
  {id:'speed',title:'Rapidité',icon:'⚽',text:'Attrape Paris, évite Arsenal, fuis l’OM.'},
  {id:'bus',title:'Bus des supporters',icon:'🚌',text:'File vers le Parc, évite les bouchons.'},
  {id:'quiz',title:'Quiz',icon:'📖',text:'Réponds avant la fin du chrono.'},
  {id:'memory',title:'Mémoire',icon:'🧩',text:'Retrouve les paires secrètes.'},
  {id:'decode',title:'Décryptage',icon:'🔍',text:'Remets les mots dans l’ordre.'},
  {id:'shoot',title:'Shoot final',icon:'🥅',text:'5 tirs pour viser juste.'}
];
const QUIZ={
  rose:[['Quel surnom donne-t-on souvent au trophée de la Ligue des Champions ?',['la coupe aux grandes oreilles','la casserole dorée','le vase magique'],0],['Une grande soirée européenne commence souvent par...',['un hymne très connu','une berceuse','un silence total'],0],['Dans un gros match, les supporters sortent souvent...',['les écharpes','les palmes','les couettes'],0],['Quand deux équipes sont à égalité après 90 minutes, il peut y avoir...',['des prolongations','un goûter','un tirage au sort de cartables'],0],['Pour vivre une finale à fond, il faut surtout...',['être tous ensemble','rester chacun dans son coin','éteindre l’ambiance'],0]],
  gustave:[['Combien de joueurs une équipe aligne au coup d’envoi ?',['11','7','18'],0],['Une passe qui mène au but est une passe...',['décisive','invisible','molle'],0],['Un tir dans l’angle haut du but s’appelle souvent...',['une lucarne','un placard','une fenêtre'],0],['Le gardien peut utiliser ses mains dans...',['sa surface','les tribunes','le bus'],0],['Dans une finale, si personne ne marque en prolongation, on peut finir par...',['des tirs au but','un concours de grimaces','une bataille de coussins'],0]],
  jacques:[['Quand le ballon rentre dans le but, on crie...',['But !','Chut !','Plouf !'],0],['Un supporter porte souvent une...',['écharpe','bouée','couronne'],0],['Le coup d’envoi lance...',['le match','le dessert','la sieste'],0],['Dans PSG contre Arsenal, Arsenal vient de...',['Londres','Rome','Mars'],0],['Le meilleur réflexe face à un piège de l’OM dans le jeu, c’est de...',['l’éviter','cliquer dessus','l’encourager'],0]]
};
const WORDS={rose:['ROSE','ETOILE','SECRET','MISSION','BILLET'],gustave:['PASSE','TACTIQUE','STRATEGE','TROPHEE','PARIS'],jacques:['TURBO','BALLON','HEROS','BUT','PARC']};
const PAIRS=['⚽','🏟️','🎟️','🔐','⭐','🏆'];
const fresh=()=>({rose:0,gustave:0,jacques:0});
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function load(){try{return JSON.parse(localStorage.getItem('brigade30mai'))||fresh()}catch{return fresh()}}
function playVictory(){const a=new Audio('/victory.mp3');a.volume=.95;return a.play().catch(()=>{});}

export default function App(){
  const[screen,setScreen]=useState('home'),[active,setActive]=useState('rose'),[scores,setScores]=useState(load),[mission,setMission]=useState('speed'),[last,setLast]=useState(null);
  const player=PLAYERS.find(p=>p.id===active),total=Object.values(scores).reduce((a,b)=>a+b,0),unlocked=total>=TARGET_TEAM&&PLAYERS.every(p=>scores[p.id]>=TARGET_PLAYER);
  useEffect(()=>localStorage.setItem('brigade30mai',JSON.stringify(scores)),[scores]);
  const add=(points,label)=>{const safe=Math.max(0,Math.min(120,Math.round(points||0)));setScores(s=>({...s,[active]:clamp(s[active]+safe,0,9999)}));setLast({points:safe,label,name:player.name});setScreen('missions')};
  const screens={home:<Home setScreen={setScreen}/>,team:<Team active={active}setActive={setActive}scores={scores}setScreen={setScreen}/>,missions:<Missions player={player}scores={scores}total={total}setMission={setMission}setScreen={setScreen}last={last}/>,carnet:<Carnet scores={scores}total={total}setScreen={setScreen}/>,final:<Final scores={scores}total={total}unlocked={unlocked}setScreen={setScreen}reset={()=>setScores(fresh())}/>,rules:<Rules setScreen={setScreen}/>};
  return <div className="app"><div className="stars"/><header><button onClick={()=>setScreen('home')}>QG</button><b>La Brigade du 30 Mai</b><button onClick={()=>setScreen('rules')}>Règles</button></header>{screen==='game'?<Game id={mission}player={player}onDone={add}onExit={()=>setScreen('missions')}/>:screens[screen]}</div>
}
function Medal({p}){return <div className="medal" style={{'--c':p.color}}><span>{AVATARS[p.id]?<img src={AVATARS[p.id]} alt={p.name}/>:p.avatar}</span></div>}
function Bar({v,t}){return <div className="bar"><i style={{width:clamp(v/t*100,0,100)+'%'}}/></div>}
function Title({n,t,s}){return <div className="title"><small>{n}.</small><h1>{t}</h1>{s&&<p>{s}</p>}</div>}
function Home({setScreen}){return <main className="home"><div className="crest"><small>Alerte surprise exceptionnelle</small><strong>Mission<br/>30 Mai</strong><em>🔐</em></div><section className="panel introPanel"><h2>Rose, Gustave et Jacques...</h2><p>Tonton Paul vous a préparé une surprise vraiment exceptionnelle pour le samedi 30 mai.</p><p>Mais impossible de la découvrir tout de suite : elle est enfermée dans le coffre final.</p><p>Pour l’ouvrir, vous devrez travailler en équipe, réussir les missions, gagner des points et débloquer des indices au cours de la partie.</p><p><b>Chaque indice vous rapprochera du secret. Le coffre ne s’ouvrira que si toute la Brigade progresse ensemble.</b></p></section><div className="teamrow">{PLAYERS.map(p=><Medal key={p.id}p={p}/>)}</div><button className="gold"onClick={()=>setScreen('team')}>Lancer la mission</button><nav><button onClick={()=>setScreen('team')}>Équipe</button><button onClick={()=>setScreen('carnet')}>Indices</button><button onClick={()=>setScreen('final')}>Coffre</button></nav></main>}
function Team({active,setActive,scores,setScreen}){return <main><Title n="2"t="Notre équipe"s="Choisis ton héros"/><div className="cards">{PLAYERS.map(p=><button key={p.id}className={'card '+(active===p.id?'on':'')}onClick={()=>setActive(p.id)}><Medal p={p}/><h2>{p.name}</h2><p>{p.role}</p><Bar v={scores[p.id]}t={TARGET_PLAYER}/><b>{scores[p.id]} / {TARGET_PLAYER}</b></button>)}</div><button className="gold"onClick={()=>setScreen('missions')}>Voir les missions</button></main>}
function Missions({player,scores,total,setMission,setScreen,last}){return <main><Title n="3"t="Missions"s="Gagne des points et ouvre les indices"/><section className="panel hero"><Medal p={player}/><div><b>{player.name} joue</b><Bar v={scores[player.id]}t={TARGET_PLAYER}/><span>{scores[player.id]} / {TARGET_PLAYER}</span></div></section>{last&&<div className="toast">+{last.points} points pour {last.name} — {last.label}</div>}<div className="grid">{MISSIONS.map(m=><button key={m.id}className="mission"onClick={()=>{setMission(m.id);setScreen('game')}}><span>{m.icon}</span><b>{m.title}</b><small>{m.text}</small></button>)}</div><section className="panel"><b>Total équipe : {total} / {TARGET_TEAM}</b><Bar v={total}t={TARGET_TEAM}/></section><nav><button onClick={()=>setScreen('team')}>Équipe</button><button onClick={()=>setScreen('carnet')}>Indices</button><button onClick={()=>setScreen('final')}>Coffre</button></nav></main>}
function Carnet({scores,total,setScreen}){const checks=[scores.rose>=100,scores.gustave>=100,scores.jacques>=100,total>=500,total>=TARGET_TEAM],clues=['Samedi 30 mai','Une soirée événement','Ambiance de stade','Un lieu mythique','Cadeau final'];return <main><Title n="4"t="Carnet secret"/><section className="paper">{clues.map((c,i)=><div key={c}><span>Indice {i+1}</span><b>{checks[i]?c:'À découvrir'}</b><em>{checks[i]?'✓':'🔒'}</em></div>)}</section><button className="gold"onClick={()=>setScreen('missions')}>Retour aux missions</button></main>}
function Final({scores,total,unlocked,setScreen,reset}){const[opened,setOpened]=useState(false);const open=()=>{playVictory();setOpened(true)};return <main className="finalPage"><Title n="11"t="Coffre final"s={unlocked?(opened?'Secret révélé':'Prêt à ouvrir'):'Coffre verrouillé'}/>{!unlocked?<section className="panel final lockedFinal"><div className="bigChest">🔐</div><h2>Le coffre résiste encore...</h2>{PLAYERS.map(p=><p key={p.id}>{scores[p.id]>=TARGET_PLAYER?'✅':'🔒'} {p.name} : {scores[p.id]} / {TARGET_PLAYER}</p>)}<p>{total>=TARGET_TEAM?'✅':'🔒'} Équipe : {total} / {TARGET_TEAM}</p></section>:!opened?<section className="panel final finalReady"><div className="bigChest pulse">🎁</div><h2>Le coffre est prêt !</h2><p>La Brigade a réussi. Appuyez pour ouvrir le coffre final et découvrir la surprise de Tonton Paul.</p><div className="teamrow">{PLAYERS.map(p=><Medal key={p.id}p={p}/>)}</div><button className="gold"onClick={open}>Ouvrir le coffre</button></section>:<section className="panel final finalReveal"><div className="sparkleLayer"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div className="confetti">✦ ✨ ★ ✨ ✦</div><h2>Surprise !</h2><div className="revealHero"></div><p className="revealText">Vivez tous ensemble la finale de ce soir sur écran géant au Parc des Princes.</p><div className="ticketBox"><b>Rendez-vous</b><strong>Samedi 30 mai</strong><span>La Brigade au complet</span></div></section>}<button className="gold"onClick={()=>setScreen('missions')}>Retour</button><button onClick={reset}>Remettre à zéro</button></main>}
function Rules({setScreen}){return <main><Title n="12"t="Règles"/><section className="paper"><p>Chaque héros doit atteindre son score personnel.</p><p>L’équipe doit atteindre le score collectif.</p><p>Les indices se débloquent dans le carnet au cours de la partie.</p><p>Le coffre final révèle la surprise préparée par Tonton Paul.</p></section><button className="gold"onClick={()=>setScreen('home')}>Retour au QG</button></main>}
function Frame({title,player,time,score,onExit,children}){return <main><div className="gameHead"><Medal p={player}/><h1>{title}</h1><b>{time}s</b><b>{score}</b></div>{children}<button onClick={onExit}>Retour aux missions</button></main>}
function Game({id,player,onDone,onExit}){const map={speed:Speed,bus:BusGame,quiz:QuizGame,memory:Memory,decode:Decode,shoot:Shoot};const C=map[id]||Speed;return <C player={player}onDone={onDone}onExit={onExit}/>}
function Speed({player,onDone,onExit}){const[time,setTime]=useState(18),[score,setScore]=useState(0),[targets,setTargets]=useState([]),[pop,setPop]=useState(null);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const pick=()=>{const r=Math.random();return r<.58?'psg':r<.87?'arsenal':'om'};const t=setInterval(()=>setTime(x=>x-1),1000),s=setInterval(()=>{const id=Math.random(),type=pick(),target={id,type,x:9+Math.random()*78,y:14+Math.random()*62};setTargets(a=>[...a,target].slice(-5));setTimeout(()=>setTargets(a=>a.filter(z=>z.id!==id)),850+Math.random()*650)},620);return()=>{clearInterval(t);clearInterval(s)}},[]);useEffect(()=>{if(time<=0)onDone(Math.min(ref.current,120),'Rapidité')},[time]);const hit=t=>{let delta=0,label='',kind=t.type;if(t.type==='psg'){delta=12;label='+12'}else if(t.type==='arsenal'){delta=-8;label='-8'}else{label='Retour à zéro !'};setScore(s=>t.type==='om'?0:clamp(s+delta,0,120));setPop({id:Math.random(),x:t.x,y:t.y,label,kind});setTimeout(()=>setPop(null),650);setTargets(a=>a.filter(z=>z.id!==t.id))};return <Frame title="Rapidité"player={player}time={Math.max(time,0)}score={score}onExit={onExit}><section className="rapiditeHelp"><b>Paris +12</b><span>Arsenal -8</span><em>OM = zéro</em></section><div className="rapiditeArena"><div className="stadiumGlow"/><div className="pitchLines"/><div className="goalNet"/>{targets.map(t=><button key={t.id}className={'crestTarget '+t.type}style={{left:t.x+'%',top:t.y+'%'}}onClick={()=>hit(t)}>{t.type==='psg'?<><strong>PARIS</strong><small>SG</small></>:t.type==='arsenal'?<><strong>ARS</strong><small>-8</small></>:<><strong>OM</strong><small>0</small></>}</button>)}{pop&&<div key={pop.id}className={'scorePop '+pop.kind}style={{left:pop.x+'%',top:pop.y+'%'}}>{pop.label}</div>}</div></Frame>}
function BusGame({player,onDone,onExit}){const[time,setTime]=useState(25),[lane,setLane]=useState(1),[score,setScore]=useState(0),[items,setItems]=useState([]);const laneRef=useRef(1),scoreRef=useRef(0);useEffect(()=>{laneRef.current=lane},[lane]);useEffect(()=>{scoreRef.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000),s=setInterval(()=>{const id=Math.random();setItems(a=>[...a,{id,lane:Math.floor(Math.random()*3),y:-10,type:Math.random()<.55?'star':Math.random()<.78?'ticket':'jam'}])},850),m=setInterval(()=>setItems(a=>{const keep=[];a.forEach(i=>{const ny=i.y+6;const hit=ny>76&&ny<88&&i.lane===laneRef.current;if(hit){setScore(sc=>{const delta=i.type==='jam'?-15:i.type==='ticket'?12:5;return clamp(sc+delta,0,120)})}else if(ny<110)keep.push({...i,y:ny})});return keep}),110);return()=>{clearInterval(t);clearInterval(s);clearInterval(m)}},[]);useEffect(()=>{if(time<=0)onDone(Math.min(scoreRef.current,120),'Bus des supporters')},[time]);return <Frame title="Bus"player={player}time={Math.max(time,0)}score={score}onExit={onExit}><section className="bus"><div className="road">{[0,1,2].map(x=><i key={x}className="lane"/>)}{items.map(i=><span key={i.id}className={'roadItem '+i.type}style={{left:(16+i.lane*34)+'%',top:i.y+'%'}}>{i.type==='jam'?'🚧':i.type==='ticket'?'🎟️':'⭐'}</span>)}<span className="supporterBus"style={{left:(16+lane*34)+'%'}}>🚌</span></div><div className="busControls"><button onClick={()=>setLane(l=>clamp(l-1,0,2))}>◀</button><button onClick={()=>setLane(l=>clamp(l+1,0,2))}>▶</button></div><p>Étoile +5 · Billet +12 · Bouchon -15 · max 120</p></section></Frame>}
function QuizGame({player,onDone,onExit}){const[time,setTime]=useState(45),[idx,setIdx]=useState(0),[score,setScore]=useState(0),[qs]=useState(()=>shuffle(QUIZ[player.id]).slice(0,5));const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(time<=0||idx>=qs.length)onDone(ref.current,'Quiz')},[time,idx]);if(idx>=qs.length)return null;const q=qs[idx];return <Frame title="Quiz"player={player}time={Math.max(time,0)}score={score}onExit={onExit}><section className="panel"><h2>{q[0]}</h2>{q[1].map((a,i)=><button key={a}onClick={()=>{setScore(s=>s+(i===q[2]?18:0));setIdx(x=>x+1)}}>{a}</button>)}</section></Frame>}
function Memory({player,onDone,onExit}){const[time,setTime]=useState(50),[cards,setCards]=useState(()=>shuffle([...PAIRS,...PAIRS]).map((v,i)=>({id:i,v,open:false,found:false}))),[first,setFirst]=useState(null),[score,setScore]=useState(0),[lock,setLock]=useState(false);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(time<=0||cards.every(c=>c.found))onDone(ref.current,'Mémoire')},[time,cards]);const flip=c=>{if(lock||c.open||c.found)return;setCards(a=>a.map(x=>x.id===c.id?{...x,open:true}:x));if(!first){setFirst(c);return}if(first.v===c.v){setScore(s=>s+15);setCards(a=>a.map(x=>x.id===first.id||x.id===c.id?{...x,found:true,open:true}:x));setFirst(null)}else{setLock(true);setTimeout(()=>{setCards(a=>a.map(x=>x.id===first.id||x.id===c.id?{...x,open:false}:x));setFirst(null);setLock(false)},700)}};return <Frame title="Mémoire"player={player}time={Math.max(time,0)}score={score}onExit={onExit}><div className="mem">{cards.map(c=><button key={c.id}onClick={()=>flip(c)}>{(c.open||c.found)?c.v:'?'}</button>)}</div></Frame>}
function Decode({player,onDone,onExit}){const list=WORDS[player.id];const[time,setTime]=useState(45),[idx,setIdx]=useState(0),[built,setBuilt]=useState(''),[score,setScore]=useState(0);const word=list[idx]||'',letters=useMemo(()=>shuffle(word.split('')),[word]);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(time<=0||idx>=list.length)onDone(ref.current,'Décryptage')},[time,idx]);if(idx>=list.length)return null;return <Frame title="Décryptage"player={player}time={Math.max(time,0)}score={score}onExit={onExit}><section className="panel"><div className="slots">{word.split('').map((_,i)=><span key={i}>{built[i]||''}</span>)}</div>{letters.map((l,i)=><button key={l+i}onClick={()=>{const n=built+l;if(word.startsWith(n)){setBuilt(n);if(n===word){setScore(s=>s+18);setTimeout(()=>{setBuilt('');setIdx(x=>x+1)},400)}}else setBuilt('')}}>{l}</button>)}</section></Frame>}
function Shoot({player,onDone,onExit}){const[time,setTime]=useState(30),[score,setScore]=useState(0),[pos,setPos]=useState(0),[dir,setDir]=useState(1),[shots,setShots]=useState(5);const ref=useRef(0);useEffect(()=>{ref.current=score},[score]);useEffect(()=>{const t=setInterval(()=>setTime(x=>x-1),1000),m=setInterval(()=>setPos(p=>{let n=p+dir*4;if(n>100||n<0){setDir(d=>-d);n=clamp(n,0,100)}return n}),45);return()=>{clearInterval(t);clearInterval(m)}},[dir]);useEffect(()=>{if(time<=0||shots<=0)onDone(Math.min(ref.current,120),'Shoot final')},[time,shots]);return <Frame title="Shoot"player={player}time={Math.max(time,0)}score={score}onExit={onExit}><section className="panel shoot"><p>{shots} tirs restants</p><div className="gauge"><i style={{left:pos+'%'}}/></div><button className="gold"disabled={shots<=0}onClick={()=>{const d=Math.abs(pos-50);setScore(s=>clamp(s+(d<8?24:d<20?12:0),0,120));setShots(x=>x-1)}}>Tirer !</button></section></Frame>}
